### ISSUE TITLE
can't view sample

### ISSUE THREAD

**Issue by johndpope** [EXPNUNI/enuSpace-js#1]
when I click on index.html - I get login screen.

<img width="937" alt="screen shot 2018-07-03 at 9 41 59 pm" src="https://user-images.githubusercontent.com/289994/42252307-fc2c6acc-7f09-11e8-9eba-7cc6faf7aee9.png">

I'll dig around to see if I can fix.

**Comment by BrightJoy** [comment]
If you want run sample project.

1. enuSpace application program download. (recommand version mars - 2.0.6.86)
2. run enuSpace and open sample project
3. click Web Server button. run Web Browser button (http://127.0.0.1:8080/www/index.html)
4. login 


https://expnuni.gitbooks.io/enuspace/content/download.html
https://expnuni.gitbooks.io/enuspace/content/tutorial/web-interface.html
